/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doanxemay;

import Connectdatabase.Connect;
import Controll.DanhsachKhachHang;
import Controll.Dulieubang;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.util.Calendar;
/**
 *  Giao diện Khách hàng
 * 
 * @author: Phan Duy Tuấn
 */
public class GUIKhachHang extends javax.swing.JFrame {
    public static String sql = "Select * from dbo.[KhachHang]";
    public static String makh;
    /**
     * Chức năng: Tạo giao diện khách hàng
     * 
     * author : Phan Duy Tuấn
     * 
     * Ngày : 4/10/2019
     */
    
    public GUIKhachHang() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        showDuLieu();
        DanhsachKhachHang.loadDuLieuKhachHang(sql, tblKhachHang);
        this.Chon_ngaysinh.setDateFormatString("dd/MM/yyyy");
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");     
        timkiem();
        Crt(false);
    }
    /**
     * Ẩn hiện các ô nhập và nút trên giao diện
     * 
     * @param b : Giá trị true hoặc false
     * 
     * Ngày 6/10/2019
     */
    public void Crt(boolean b){
        txttenkh.setEnabled(b);
        txtsodienthoai.setEnabled(b);
        
        txtcmnd.setEnabled(b);
        //lblngaysinh.setEnabled(b);
        Chon_ngaysinh.setEnabled(b);
        txtemail.setEnabled(b);
        btnluu.setEnabled(b);
        btnsua.setEnabled(b);
        btnxoa.setEnabled(b);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblxe = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblhoadon = new javax.swing.JLabel();
        lbldangxuat = new javax.swing.JLabel();
        lblkhachhang = new javax.swing.JLabel();
        lblnhanvien = new javax.swing.JLabel();
        lblnhacc = new javax.swing.JLabel();
        lblthongke = new javax.swing.JLabel();
        lblthongtin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblthoat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtsodienthoai = new javax.swing.JTextField();
        lblmakh = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnluu = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        txttenkh = new javax.swing.JTextField();
        txtcmnd = new javax.swing.JTextField();
        Chon_ngaysinh = new com.toedter.calendar.JDateChooser();
        txtemail = new javax.swing.JTextField();
        cmbloaitk = new javax.swing.JComboBox<>();
        txttimkiem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(76, 95, 107));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 743));

        label1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Phan Duy Tuấn");

        class RoundedPanel extends JPanel
        {
            private Color backgroundColor;
            private int cornerRadius = 15;
            public RoundedPanel(LayoutManager layout, int radius) {
                super(layout);
                cornerRadius = radius;
            }
            public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
                super(layout);
                cornerRadius = radius;
                backgroundColor = bgColor;
            }
            public RoundedPanel(int radius) {
                super();
                cornerRadius = radius;

            }
            public RoundedPanel(int radius, Color bgColor) {
                super();
                cornerRadius = radius;
                backgroundColor = bgColor;
            }
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Dimension arcs = new Dimension(cornerRadius, cornerRadius);
                int width = getWidth();
                int height = getHeight();
                Graphics2D graphics = (Graphics2D) g;
                graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                //Draws the rounded panel with borders.
                if (backgroundColor != null) {
                    graphics.setColor(backgroundColor);
                } else {
                    graphics.setColor(getBackground());
                }
                graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
                graphics.setColor(getForeground());
                //            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
                //
            }
        }

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/Anhdaidien.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lblxe.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblxe.setForeground(new java.awt.Color(255, 255, 255));
        lblxe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblxe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/xemay_khongchon.png"))); // NOI18N
        lblxe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblxe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblxeMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("duytuan");

        lblhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/HoaDon_khongchon.png"))); // NOI18N
        lblhoadon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhoadonMouseClicked(evt);
            }
        });

        lbldangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dangxuat.png"))); // NOI18N
        lbldangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldangxuatMouseClicked(evt);
            }
        });

        lblkhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/khachhang_chon.png"))); // NOI18N

        lblnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/nhanvien_khongchon.png"))); // NOI18N
        lblnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnhanvienMouseClicked(evt);
            }
        });

        lblnhacc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/NhaCC_khongchon.png"))); // NOI18N
        lblnhacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnhaccMouseClicked(evt);
            }
        });

        lblthongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/Khongchon_Thongke.png"))); // NOI18N
        lblthongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblthongkeMouseClicked(evt);
            }
        });

        lblthongtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/Thongtin_khongchon.png"))); // NOI18N
        lblthongtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblthongtinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblnhacc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblkhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbldangxuat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblhoadon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblxe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblthongke)
                    .addComponent(lblthongtin))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lbldangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(lblxe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnhacc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblthongke)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblthongtin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        lblthoat.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        lblthoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        lblthoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblthoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblthoatMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 95, 107));
        jLabel1.setText("Khách hàng");

        tblKhachHang.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKhachHang.setRowHeight(30);
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(76, 95, 107));
        jLabel3.setText("Mã khách hàng");

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(76, 95, 107));
        jLabel4.setText("Tên khách hàng");

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(76, 95, 107));
        jLabel5.setText("Số điện thoại");

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(76, 95, 107));
        jLabel6.setText("CMND");

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(76, 95, 107));
        jLabel7.setText("Ngày sinh");

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(76, 95, 107));
        jLabel8.setText("Email");

        txtsodienthoai.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtsodienthoai.setForeground(new java.awt.Color(76, 95, 107));
        txtsodienthoai.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));
        txtsodienthoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsodienthoaiActionPerformed(evt);
            }
        });

        lblmakh.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblmakh.setForeground(new java.awt.Color(76, 95, 107));
        lblmakh.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));

        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/b_themxe.png"))); // NOI18N
        btnthem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));
        btnthem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/chinhsua.png"))); // NOI18N
        btnsua.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));
        btnsua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnluu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/luu.png"))); // NOI18N
        btnluu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));
        btnluu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/xoa.png"))); // NOI18N
        btnxoa.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));
        btnxoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        txttenkh.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txttenkh.setForeground(new java.awt.Color(76, 95, 107));
        txttenkh.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));

        txtcmnd.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtcmnd.setForeground(new java.awt.Color(76, 95, 107));
        txtcmnd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));

        Chon_ngaysinh.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N

        txtemail.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtemail.setForeground(new java.awt.Color(76, 95, 107));
        txtemail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        cmbloaitk.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        cmbloaitk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên khách hàng", "Số điện thoại", "CMND" }));

        txttimkiem.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txttimkiem.setText("Tìm kiếm");
        txttimkiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttimkiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttimkiemFocusLost(evt);
            }
        });
        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });
        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimkiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(cmbloaitk, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(lblthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txttenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblmakh, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtsodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcmnd)
                            .addComponent(txtemail)
                            .addComponent(Chon_ngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btnthem)
                        .addGap(75, 75, 75)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnluu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addGap(174, 174, 174))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttimkiem)
                    .addComponent(cmbloaitk))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblmakh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtcmnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(Chon_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(168, 168, 168)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnluu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnthem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1097, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Chuyển sang giao diện xe máy
     * 
     * 
     * Ngày: 4/10/2019
     */
    private void lblxeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblxeMouseClicked
        new GUIXeMay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblxeMouseClicked
    /**
     * Chuyển sang giao diện hóa đơn
     * 
     * 
     * Ngày: 4/10/2019
     */
    private void lblhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhoadonMouseClicked
        new GUIHoaDon().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblhoadonMouseClicked
    
    private void lblthoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthoatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblthoatMouseClicked
    /**
     * Hiển thị thông tin của một khách hàng lên giao diện
     * 
     * 
     * Ngày: 4/10/2019
     */
    private void showDuLieu(){
        Connection connection= Connect.getConnect();
            String query="SELECT * from dbo.[KhachHang]";
        try {           
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {        
                this.lblmakh.setText(rs.getString("maKhachHang"));                   
                this.txttenkh.setText(rs.getString("tenKhachHang"));
                this.Chon_ngaysinh.setDate(rs.getDate("ngaySinh"));
                this.txtsodienthoai.setText(rs.getString("soDienThoai"));
                this.txtcmnd.setText(rs.getString("soCMND"));
                this.txtemail.setText(rs.getString("email"));
            }
            
        } catch (Exception e) {
            e.printStackTrace(); 
        }
    }
    /**
     * Hiển thị thông tin của khách hàng khi nhấn vào thông tin khách hàng trong bảng
     * 
     * Ngày: 6/10/2019
     */
    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        try {
            int row= this.tblKhachHang.getSelectedRow();
            Crt(false);
            btnluu.setEnabled(false);
            btnxoa.setEnabled(true);
            btnsua.setEnabled(true);
            SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
            String IDrow = (this.tblKhachHang.getModel().getValueAt(row, 1)).toString();
            String sql1="Select * from dbo.[KhachHang] where maKhachHang='"+IDrow+"'";
            ResultSet rs = Dulieubang.ShowTextField(sql1);
            if(rs.next()){
                makh= rs.getString("maKhachHang");
                this.lblmakh.setText(rs.getString("maKhachHang"));              
                this.txttenkh.setText(rs.getString("tenKhachHang"));
                this.txtsodienthoai.setText(rs.getString("soDienThoai"));
                //this.txtdiachi.setText(rs.getString("diaChi"));
                this.txtcmnd.setText(rs.getString("soCMND"));
                this.Chon_ngaysinh.setDate(rs.getDate("ngaySinh"));
                this.txtemail.setText(rs.getString("email"));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void txtsodienthoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsodienthoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsodienthoaiActionPerformed
    
    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        Crt(true);
        btnluu.setEnabled(true);
        
        this.lblmakh.setText("Tự động phát sinh");
        this.txttenkh.setText("");
        this.txtsodienthoai.setText("");
        
        this.txtsodienthoai.setText("");
        this.txtcmnd.setText("");
        
        this.txtemail.setText("");
        this.txttenkh.requestFocus();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        
        btnluu.setEnabled(true);
        btnxoa.setEnabled(false);
        if(lblmakh.getText().length()==0 || lblmakh.getText()=="Tự động phát sinh"){
            JOptionPane.showMessageDialog(null, "Bạn phải chọn xe cần sửa","Thông báo",1);
        }
        else{
            Crt(true);
        }
    }//GEN-LAST:event_btnsuaActionPerformed
    /**
     * Lưu thông tin khách hàng sau khi sửa hoặc thêm
     * 
     * Ngày: 4/10/2019
     * 
     * @author : Phan Duy Tuấn
     */
    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
        /*java.util.Date ngaysinh =  this.Chon_ngaysinh.getDate();
        Date ns = (Date) ngaysinh;*/
        java.util.Date date = Chon_ngaysinh.getDate();
        String ngaysinh = DateFormat.getDateInstance().format(date);
        int error=0;
        if(this.txttenkh.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Tên khách hàng không được bỏ trống");
            error=1;
        }
        else{
            error=0;
        }
        int error2=0;
        if(this.txtsodienthoai.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Số điện thoại không được bỏ trống");
            error2=1;
        }
        else{
            if(this.txtsodienthoai.getText().length()!=10){
                JOptionPane.showMessageDialog(this, "Số điện thoại phải có 10 kí tự số");
                error2=1;
            }
            else{
                error2=0;
            }
            
        }
        int error3=0;
        if(this.txtcmnd.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Số CMND không được bỏ trống");
            error3=1;
        }
        else{
            if(txtcmnd.getText().length()==9 || txtcmnd.getText().length()==13){
                error3=0;
            }
            else{
                JOptionPane.showMessageDialog(this, "Số CMND phải có 9 hoặc 13 kí tự số");
                error3=1;
            }
        }
        if(error==1 || error2==1 || error3==1){
            if(this.lblmakh.getText()=="Tự động phát sinh"){
                JOptionPane.showMessageDialog(this, "Thêm thông tin khách hàng thất bại");
            }
            else{
                JOptionPane.showMessageDialog(this, "Sửa thông tin khách hàng thất bại");
            }
        }
        else{
            if(this.lblmakh.getText()=="Tự động phát sinh"){
                DanhsachKhachHang.ThemKhachHang(makh, this.txttenkh.getText(), this.txtsodienthoai.getText(), this.txtcmnd.getText()
                        ,ngaysinh, this.txtemail.getText());
                DanhsachKhachHang.loadDuLieuKhachHang(sql, tblKhachHang);
            }
            else{
                if(this.lblmakh.getText().length()==0){
                    JOptionPane.showMessageDialog(null, "Bạn phải chọn khách hàng cần sửa","Thông báo",1);
                }
                else{
                    if(JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn sửa khách hàng có mã là "+makh+" hay không ?","Thông báo",2)==0){
                        DanhsachKhachHang.SuaKhachHang(makh, this.txttenkh.getText(), this.txtsodienthoai.getText(), this.txtcmnd.getText(), ngaysinh, this.txtemail.getText());
                        DanhsachKhachHang.loadDuLieuKhachHang(sql, tblKhachHang);
                    }

                }

            }
        }
        
    }//GEN-LAST:event_btnluuActionPerformed
    /**
     * Xóa khách hàng
     * 
     * Ngày: 4/10/2019 
     */
    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa khách hàng có mã là "+makh+" hay không ?","Thông báo",2)==0){
            DanhsachKhachHang.XoaKhachHang(makh);
            DanhsachKhachHang.loadDuLieuKhachHang(sql, tblKhachHang);
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed
    
    private void lblnhaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnhaccMouseClicked
        new GUINhaCungCap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblnhaccMouseClicked

    private void lblnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnhanvienMouseClicked
        new GUINhanVien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblnhanvienMouseClicked

    private void txttimkiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttimkiemFocusGained
        if(txttimkiem.getText().equals("Tìm kiếm")){
            this.txttimkiem.setText("");
        }
    }//GEN-LAST:event_txttimkiemFocusGained

    private void txttimkiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttimkiemFocusLost
        if(txttimkiem.getText().equals("")){
            this.txttimkiem.setText("Tìm kiếm");
        }
    }//GEN-LAST:event_txttimkiemFocusLost
    public void timkiem(){
        if(txttimkiem.getText().length()==0){
            DanhsachKhachHang.loadDuLieuKhachHang(sql, tblKhachHang);
        }
        else{
            /*if(cmbloaitk.getSelectedItem()=="Chọn thông tin tìm kiếm"){
                DanhsachKhachHang.loadDuLieuKhachHang(sql, tblKhachHang);
            }
            if(cmbloaitk.getSelectedItem()=="Tên khách hàng"){
                String sqltenkh = "Select * from dbo.[KhachHang] where tenKhachHang like '%"+this.txttimkiem.getText()+"%'";
                Dulieubang.loadDuLieu(sqltenkh, tblKhachHang);
            }
            if(cmbloaitk.getSelectedItem()=="Số điện thoại"){
                String sqlsdt = "Select * from dbo.[KhachHang] where soDienThoai like '%"+this.txttimkiem.getText()+"%'";
                DanhsachKhachHang.loadDuLieuKhachHang(sqlsdt, tblKhachHang);
            }
            if(cmbloaitk.getSelectedItem()=="CMND"){
                String sqlcmnd = "Select * from dbo.[KhachHang] where  soCMND like '%"+this.txttimkiem.getText()+"%'";
                DanhsachKhachHang.loadDuLieuKhachHang(sqlcmnd, tblKhachHang);
            }*/
            String sqltenkh = "Select * from dbo.[KhachHang] where tenKhachHang like '%"+this.txttimkiem.getText()+"%'";
            DanhsachKhachHang.loadDuLieuKhachHang(sqltenkh, tblKhachHang);
        }
    }
    /**
     * Tìm kiếm thông tin khách hàng
     * 
     * @param evt : Khách hàng
     * 
     * @author : Phan Duy Tuấn
     * 
     * Ngày : 8/10/2019
     */
    private void txttimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyReleased
        if(txttimkiem.getText().length()==0){
            DanhsachKhachHang.loadDuLieuKhachHang(sql, tblKhachHang);
        }
        else{
            if(cmbloaitk.getSelectedItem()=="Chọn thông tin tìm kiếm"){
                DanhsachKhachHang.loadDuLieuKhachHang(sql, tblKhachHang);
            }
            if(cmbloaitk.getSelectedItem()=="Tên khách hàng"){
                String sqltenkh = "Select * from dbo.[KhachHang] where tenKhachHang like '%"+this.txttimkiem.getText()+"%'";
            //DanhsachKhachHang.TimKhachHang(sqltenkh, tblKhachHang);
            DanhsachKhachHang.TimtenKhachHang(sql, tblKhachHang, this.txttimkiem.getText());
            }
            if(cmbloaitk.getSelectedItem()=="Số điện thoại"){
                String sqlsdt = "Select * from dbo.[KhachHang] where soDienThoai like '%"+this.txttimkiem.getText()+"%'";
                DanhsachKhachHang.TimsdtKhachHang(sqlsdt, tblKhachHang, this.txttimkiem.getText());
            }
            if(cmbloaitk.getSelectedItem()=="CMND"){
                String sqlcmnd = "Select * from dbo.[KhachHang] where  soCMND like '%"+this.txttimkiem.getText()+"%'";
                DanhsachKhachHang.TimcmndKhachHang(sqlcmnd, tblKhachHang, this.txttimkiem.getText());
            }
            
        }

    }//GEN-LAST:event_txttimkiemKeyReleased

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimkiemActionPerformed
    /**
     * Đăng xuất khỏi chương trình
     * 
     * Ngày : 6/10/2019
     */
    private void lbldangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuatMouseClicked
        new JFrameGiaodien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbldangxuatMouseClicked

    private void lblthongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthongkeMouseClicked
        new GUIThongke().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblthongkeMouseClicked

    private void lblthongtinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthongtinMouseClicked
        new GUIThongtin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblthongtinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Chon_ngaysinh;
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cmbloaitk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JLabel lbldangxuat;
    private javax.swing.JLabel lblhoadon;
    private javax.swing.JLabel lblkhachhang;
    private javax.swing.JLabel lblmakh;
    private javax.swing.JLabel lblnhacc;
    private javax.swing.JLabel lblnhanvien;
    private javax.swing.JLabel lblthoat;
    private javax.swing.JLabel lblthongke;
    private javax.swing.JLabel lblthongtin;
    private javax.swing.JLabel lblxe;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtcmnd;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtsodienthoai;
    private javax.swing.JTextField txttenkh;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
