/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doanxemay;

import javax.swing.JFrame;
import Connectdatabase.Connect;
import Controll.DanhsachHoaDon;
import Controll.DanhsachNhaCungCap;
import Controll.DanhsachXe;
import Controll.Dulieubang;
import static doanxemay.GUIHoaDon.sql;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.DecimalFormat;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.primefaces.component.autocomplete.AutoComplete;
/**
 *
 * @author DELL
 */
public class GUIThongke extends javax.swing.JFrame {

    /**
     * Creates new form GUIThongke
     */
    public GUIThongke() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        DanhsachHoaDon.loadDuLieuThongke(sql, tblNhaCungCap);
        ShowDuLieu();
        AutoCompleteDecorator.decorate(cmbnam);
        AutoCompleteDecorator.decorate(cmbthang);
        tieudetk.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblxe = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblhoadon = new javax.swing.JLabel();
        lbldangxuat = new javax.swing.JLabel();
        lblkhachhang = new javax.swing.JLabel();
        lblnhanvien = new javax.swing.JLabel();
        lblnhacc = new javax.swing.JLabel();
        lblthongke = new javax.swing.JLabel();
        lblthongtin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblthoat = new javax.swing.JLabel();
        tieudetk = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhaCungCap = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmbthang = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbnam = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblxemtk = new javax.swing.JLabel();
        lbltongdoanhthu = new javax.swing.JLabel();
        lbltongsl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbltenxe = new javax.swing.JLabel();
        lblsoluong = new javax.swing.JLabel();
        lblsl = new javax.swing.JLabel();
        lblhinhxe = new javax.swing.JLabel();
        lblxemanh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(76, 95, 107));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 743));

        label1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Phan Duy Tuấn");

        class RoundedPanel extends JPanel
        {
            private Color backgroundColor;
            private int cornerRadius = 15;
            public RoundedPanel(LayoutManager layout, int radius) {
                super(layout);
                cornerRadius = radius;
            }
            public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
                super(layout);
                cornerRadius = radius;
                backgroundColor = bgColor;
            }
            public RoundedPanel(int radius) {
                super();
                cornerRadius = radius;

            }
            public RoundedPanel(int radius, Color bgColor) {
                super();
                cornerRadius = radius;
                backgroundColor = bgColor;
            }
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Dimension arcs = new Dimension(cornerRadius, cornerRadius);
                int width = getWidth();
                int height = getHeight();
                Graphics2D graphics = (Graphics2D) g;
                graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                //Draws the rounded panel with borders.
                if (backgroundColor != null) {
                    graphics.setColor(backgroundColor);
                } else {
                    graphics.setColor(getBackground());
                }
                graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
                graphics.setColor(getForeground());
                //            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
                //
            }
        }

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/Anhdaidien.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lblxe.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblxe.setForeground(new java.awt.Color(255, 255, 255));
        lblxe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblxe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/xemay_khongchon.png"))); // NOI18N
        lblxe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblxe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblxeMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("duytuan");

        lblhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/HoaDon_khongchon.png"))); // NOI18N
        lblhoadon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhoadonMouseClicked(evt);
            }
        });

        lbldangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dangxuat.png"))); // NOI18N
        lbldangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldangxuatMouseClicked(evt);
            }
        });

        lblkhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/khachhang_khongchon.png"))); // NOI18N
        lblkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblkhachhangMouseClicked(evt);
            }
        });

        lblnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/nhanvien_khongchon.png"))); // NOI18N
        lblnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnhanvienMouseClicked(evt);
            }
        });

        lblnhacc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/NhaCC_khongchon.png"))); // NOI18N
        lblnhacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnhaccMouseClicked(evt);
            }
        });

        lblthongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/Chon_Thongke.png"))); // NOI18N

        lblthongtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/Thongtin_khongchon.png"))); // NOI18N
        lblthongtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblthongtinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbldangxuat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhoadon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblxe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblthongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblkhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblnhacc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblthongtin)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lbldangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(lblxe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnhacc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblthongke, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblthongtin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        lblthoat.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        lblthoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        lblthoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblthoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblthoatMouseClicked(evt);
            }
        });

        tieudetk.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        tieudetk.setForeground(new java.awt.Color(76, 95, 107));
        tieudetk.setText("Thống kê");

        tblNhaCungCap.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        tblNhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNhaCungCap.setRowHeight(30);
        tblNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhaCungCapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhaCungCap);

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel2.setText("Tháng");

        cmbthang.addItem("Tất cả");
        cmbthang.setEditable(true);
        cmbthang.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        for(int i=1; i<= 12; i++){
            cmbthang.addItem(""+i+"");
        }

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel3.setText("Năm");

        cmbnam.addItem("Tất cả");
        for(int i=2019; i>=1980;i--){
            cmbnam.addItem(""+i+"");
        }
        cmbnam.setEditable(true);
        cmbnam.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel4.setText("Tổng doanh thu");

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel5.setText("Số lượng xe bán được");

        lblxemtk.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblxemtk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblxemtk.setText("Xem thống kê");
        lblxemtk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 95, 107)));
        lblxemtk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblxemtk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblxemtkMouseClicked(evt);
            }
        });

        lbltongdoanhthu.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbltongdoanhthu.setText("jLabel6");

        lbltongsl.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbltongsl.setText("jLabel7");

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel6.setText("Chiếc xe bán chạy nhất");

        lbltenxe.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lbltenxe.setText("jLabel7");

        lblsoluong.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblsoluong.setText("Số lượng");

        lblsl.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblsl.setText("jLabel7");

        lblhinhxe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 95, 107)));

        lblxemanh.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblxemanh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblxemanh.setText("Xem ảnh");
        lblxemanh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 95, 107)));
        lblxemanh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblxemanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblxemanhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(tieudetk, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbthang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(cmbnam, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(228, 228, 228)
                                .addComponent(lblxemtk, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblsoluong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbltongsl, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblsl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(lbltenxe, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                                    .addGap(48, 48, 48))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(lbltongdoanhthu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGap(9, 9, 9)))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(184, 184, 184)
                                        .addComponent(lblxemanh, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(lblhinhxe, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tieudetk, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblxemtk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbthang)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbnam, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(lbltongdoanhthu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(lbltongsl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblsoluong, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(lblsl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addComponent(lblxemanh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblhinhxe, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1073, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblxeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblxeMouseClicked
        new GUIXeMay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblxeMouseClicked

    private void lblhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhoadonMouseClicked
        new GUIHoaDon().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblhoadonMouseClicked

    private void lbldangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuatMouseClicked
        new JFrameGiaodien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbldangxuatMouseClicked

    private void lblkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblkhachhangMouseClicked
        new GUIKhachHang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblkhachhangMouseClicked

    private void lblnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnhanvienMouseClicked
        new GUINhanVien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblnhanvienMouseClicked

    private void lblthoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthoatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblthoatMouseClicked
    public void ShowDuLieu(){
        Connection connection=Connect.getConnect();
        DecimalFormat df = new DecimalFormat("#,### VNĐ");
        DecimalFormat df1 = new DecimalFormat("# Chiếc");
        try {
                    String sqlthang1= "select tongTien=sum(thanhTien),tongsl=sum(soLuong) from dbo.[HoaDon] h join dbo.[ChiTietHoaDon] ct on h.maHoaDon=ct.maHoaDon";
                    PreparedStatement ps = connection.prepareStatement(sqlthang1);
                    ResultSet rs = ps.executeQuery();
                    SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
                    while (rs.next()) {                
                        this.lbltongdoanhthu.setText(df.format(Double.parseDouble(rs.getString("tongTien"))));
                        this.lbltongsl.setText(df1.format(Double.parseDouble(rs.getString("tongsl"))));
                    }
                 } catch (Exception e) {
                     e.printStackTrace();
                 } 
            try {
                    String sqlthang2= "select top 1 ct.maXe,tongsl=sum(ct.soLuong),tenXe\n" +
                                    " from HoaDon h join ChiTietHoaDon ct on h.maHoaDon=ct.maHoaDon join XeMay x on x.maXe=ct.maXe\n" +
                                    " group by ct.maXe,tenXe\n" +
                                    " order by tongsl desc";
                    PreparedStatement ps = connection.prepareStatement(sqlthang2);
                    ResultSet rs = ps.executeQuery();
                    SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
                    while (rs.next()) {                
                        this.lbltenxe.setText(rs.getString("tenXe"));
                        this.lblsl.setText(df1.format(Double.parseDouble(rs.getString("tongsl"))));
                        /*byte[] img = rs.getBytes("imageXM");
                        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblhinhxe.getWidth(), lblhinhxe.getHeight(), Image.SCALE_SMOOTH));
                        lblhinhxe.setIcon(imageIcon);*/
                    }
                 } catch (Exception e) {
                     e.printStackTrace();
                 }
    }
    private void tblNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhaCungCapMouseClicked
        /*try {
            int row= this.tblNhaCungCap.getSelectedRow();
            Crt(false);

            btnxoa.setEnabled(true);
            btnsua.setEnabled(true);
            SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
            String IDrow = (this.tblNhaCungCap.getModel().getValueAt(row, 1)).toString();
            String sql1="Select * from dbo.[NhaCungCap] where maNhaCungCap='"+IDrow+"'";
            ResultSet rs = Dulieubang.ShowTextField(sql1);
            if(rs.next()){
                mancc= rs.getString("maNhaCungCap");
                this.lblmancc.setText(rs.getString("maNhaCungCap"));
                this.txttenncc.setText(rs.getString("tenNhaCungCap"));
                this.txtsodienthoai.setText(rs.getString("soDienThoai"));
                //this.txtdiachi.setText(rs.getString("diaChi"));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }*/
    }//GEN-LAST:event_tblNhaCungCapMouseClicked
    
    private void lblxemtkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblxemtkMouseClicked
        Connection connection= Connect.getConnect();
        DecimalFormat df = new DecimalFormat("#,### VNĐ");
        DecimalFormat df1 = new DecimalFormat("# Chiếc");
        if(cmbthang.getSelectedItem()=="Tất cả" && cmbnam.getSelectedItem()=="Tất cả"){
            try {
                    String sqlthang1= "select tongTien=sum(thanhTien),tongsl=sum(soLuong) from dbo.[HoaDon] h join dbo.[ChiTietHoaDon] ct on h.maHoaDon=ct.maHoaDon";
                    PreparedStatement ps = connection.prepareStatement(sqlthang1);
                    ResultSet rs = ps.executeQuery();
                    SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
                    while (rs.next()) {                
                        this.lbltongdoanhthu.setText(df.format(Double.parseDouble(rs.getString("tongTien"))));
                        this.lbltongsl.setText(df1.format(Double.parseDouble(rs.getString("tongsl"))));
                    }
                 } catch (Exception e) {
                     e.printStackTrace();
                 } 
            try {
                    String sqlthang2= "select top 1 ct.maXe,tongsl=sum(ct.soLuong),tenXe\n" +
                                    " from HoaDon h join ChiTietHoaDon ct on h.maHoaDon=ct.maHoaDon join XeMay x on x.maXe=ct.maXe\n" +
                                    " group by ct.maXe,tenXe\n" +
                                    " order by tongsl desc";
                    PreparedStatement ps = connection.prepareStatement(sqlthang2);
                    ResultSet rs = ps.executeQuery();
                    SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
                    while (rs.next()) {                
                        this.lbltenxe.setText(rs.getString("tenXe"));
                        this.lblsl.setText(df1.format(Double.parseDouble(rs.getString("tongsl"))));
                        /*byte[] img = rs.getBytes("imageXM");
                        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblhinhxe.getWidth(), lblhinhxe.getHeight(), Image.SCALE_SMOOTH));
                        lblhinhxe.setIcon(imageIcon);*/
                    }
                 } catch (Exception e) {
                     e.printStackTrace();
                 }
            DanhsachHoaDon.loadDuLieuThongke(sql, tblNhaCungCap);
             
        }
        else{
             if(cmbthang.getSelectedItem()=="Tất cả"){
                String sqlthang= "select * from dbo.[HoaDon] h join dbo.[ChiTietHoaDon] ct on h.maHoaDon=ct.maHoaDon join dbo.[XeMay] x on x.maXe=ct.maXe where YEAR(ngayLap)='"+this.cmbnam.getSelectedItem().toString()+"'";
                try {
                    String sqlthang1= "select tongTien=sum(thanhTien),tongsl=sum(soLuong) from dbo.[HoaDon] h join dbo.[ChiTietHoaDon] ct on h.maHoaDon=ct.maHoaDon where YEAR(ngayLap)='"+this.cmbnam.getSelectedItem().toString()+"'";
                    PreparedStatement ps = connection.prepareStatement(sqlthang1);
                    ResultSet rs = ps.executeQuery();
                    SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
                    while (rs.next()) {                
                        this.lbltongdoanhthu.setText(df.format(Double.parseDouble(rs.getString("tongTien"))));
                        this.lbltongsl.setText(df1.format(Double.parseDouble(rs.getString("tongsl"))));
                    }
                 } catch (Exception e) {
                     e.printStackTrace();
                 }
                 try {
                    String sqlthang2= "select top 1 ct.maXe,tongsl=sum(ct.soLuong),tenXe\n" +
                                    " from HoaDon h join ChiTietHoaDon ct on h.maHoaDon=ct.maHoaDon join XeMay x on x.maXe=ct.maXe where YEAR(ngayLap)='"+this.cmbnam.getSelectedItem().toString()+"'\n" +
                                    " group by ct.maXe,tenXe\n" +
                                    " order by tongsl desc";
                    PreparedStatement ps = connection.prepareStatement(sqlthang2);
                    ResultSet rs = ps.executeQuery();
                    SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
                    while (rs.next()) {                
                        this.lbltenxe.setText(rs.getString("tenXe"));
                        this.lblsl.setText(df1.format(Double.parseDouble(rs.getString("tongsl"))));
                        /*byte[] img = rs.getBytes("imageXM");
                        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblhinhxe.getWidth(), lblhinhxe.getHeight(), Image.SCALE_SMOOTH));
                        lblhinhxe.setIcon(imageIcon);*/
                    }
                 } catch (Exception e) {
                     e.printStackTrace();
                 }
                     DanhsachHoaDon.Thongketheonam(this.cmbnam.getSelectedItem().toString(), sqlthang, tblNhaCungCap);
             }
             else if(cmbnam.getSelectedItem()=="Tất cả"){
                 String sqlnam= "select * from dbo.[HoaDon] h join dbo.[ChiTietHoaDon] ct on h.maHoaDon=ct.maHoaDon join dbo.[XeMay] x on x.maXe=ct.maXe where MONTH(ngayLap)='"+this.cmbthang.getSelectedItem().toString()+"'";
                 try {
                    String sqlthang1= "select tongTien=sum(thanhTien),tongsl=sum(soLuong) from dbo.[HoaDon] h join dbo.[ChiTietHoaDon] ct on h.maHoaDon=ct.maHoaDon where MONTH(ngayLap)='"+this.cmbthang.getSelectedItem().toString()+"'";
                    PreparedStatement ps = connection.prepareStatement(sqlthang1);
                    ResultSet rs = ps.executeQuery();
                    SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
                    while (rs.next()) {                
                        this.lbltongdoanhthu.setText(df.format(Double.parseDouble(rs.getString("tongTien"))));
                        this.lbltongsl.setText(df1.format(Double.parseDouble(rs.getString("tongsl"))));
                    }
                 } catch (Exception e) {
                     e.printStackTrace();
                 }
                 try {
                    String sqlthang2= "select top 1 ct.maXe,tongsl=sum(ct.soLuong),tenXe\n" +
                                    " from HoaDon h join ChiTietHoaDon ct on h.maHoaDon=ct.maHoaDon join XeMay x on x.maXe=ct.maXe where MONTH(ngayLap)='"+this.cmbthang.getSelectedItem().toString()+"'\n" +
                                    " group by ct.maXe,tenXe\n" +
                                    " order by tongsl desc";
                    PreparedStatement ps = connection.prepareStatement(sqlthang2);
                    ResultSet rs = ps.executeQuery();
                    SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
                    while (rs.next()) {                
                        this.lbltenxe.setText(rs.getString("tenXe"));
                        this.lblsl.setText(df1.format(Double.parseDouble(rs.getString("tongsl"))));
                        /*byte[] img = rs.getBytes("imageXM");
                        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblhinhxe.getWidth(), lblhinhxe.getHeight(), Image.SCALE_SMOOTH));
                        lblhinhxe.setIcon(imageIcon);*/
                    }
                 } catch (Exception e) {
                     e.printStackTrace();
                 }
                 DanhsachHoaDon.Thongketheothang(this.cmbthang.getSelectedItem().toString(), sqlnam, tblNhaCungCap);
             }
             else{
                 String sqltk="select * from dbo.[HoaDon] h join dbo.[ChiTietHoaDon] ct on h.maHoaDon=ct.maHoaDon join dbo.[XeMay] x on x.maXe=ct.maXe where MONTH(ngayLap)='"+this.cmbthang.getSelectedItem().toString()+"' and YEAR(ngayLap)='"+this.cmbnam.getSelectedItem().toString()+"'";
                 try {
                    String sqlthang1= "select tongTien=sum(thanhTien),tongsl=sum(soLuong) from dbo.[HoaDon] h join dbo.[ChiTietHoaDon] ct on h.maHoaDon=ct.maHoaDon where MONTH(ngayLap)='"+this.cmbthang.getSelectedItem().toString()+"' and YEAR(ngayLap)='"+this.cmbnam.getSelectedItem().toString()+"'";
                    PreparedStatement ps = connection.prepareStatement(sqlthang1);
                    ResultSet rs = ps.executeQuery();
                    SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
                    while (rs.next()) {                
                        /*this.lbltongdoanhthu.setText(df.format(Double.parseDouble(rs.getString("tongTien"))));
                        this.lbltongsl.setText(rs.getString("tongsl"));*/
                        if(rs.getString("tongTien")==null  && rs.getString("tongsl")==null){
                            this.lbltongdoanhthu.setText(df.format(0));
                            this.lbltongsl.setText(df1.format(0));
                        }
                        else{
                            this.lbltongdoanhthu.setText(df.format(Double.parseDouble(rs.getString("tongTien"))));
                            this.lbltongsl.setText(df1.format(Double.parseDouble(rs.getString("tongsl"))));
                            
                        }
                    }
                 } catch (Exception e) {
                     e.printStackTrace();
                 }
                 try {
                    String sqlthang2= "select top 1 ct.maXe,tongsl=sum(ct.soLuong),tenXe\n" +
                                    " from HoaDon h join ChiTietHoaDon ct on h.maHoaDon=ct.maHoaDon join XeMay x on x.maXe=ct.maXe where MONTH(ngayLap)='"+this.cmbthang.getSelectedItem().toString()+"' and YEAR(ngayLap)='"+this.cmbnam.getSelectedItem().toString()+"'\n" +
                                    " group by ct.maXe,tenXe\n" +
                                    " order by tongsl desc";
                    PreparedStatement ps = connection.prepareStatement(sqlthang2);
                    ResultSet rs = ps.executeQuery();
                    SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
                    while (rs.next()) {                
                        this.lbltenxe.setText(rs.getString("tenXe"));
                        this.lblsl.setText(df1.format(Double.parseDouble(rs.getString("tongsl"))));
                        /*byte[] img = rs.getBytes("imageXM");
                        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblhinhxe.getWidth(), lblhinhxe.getHeight(), Image.SCALE_SMOOTH));
                        lblhinhxe.setIcon(imageIcon);*/
                    }
                 } catch (Exception e) {
                     e.printStackTrace();
                 }
                 DanhsachHoaDon.Thongke(this.cmbthang.getSelectedItem().toString(), this.cmbnam.getSelectedItem().toString(), sqltk, tblNhaCungCap);
             }
         }
    }//GEN-LAST:event_lblxemtkMouseClicked
    
    private void lblxemanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblxemanhMouseClicked
        Connection connection= Connect.getConnect();
        try {
            String sqlxe= "select * from dbo.[XeMay] where tenXe='"+this.lbltenxe.getText()+"'";
            PreparedStatement ps = connection.prepareStatement(sqlxe);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {                
                byte[] img = rs.getBytes("imageXM");
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblhinhxe.getWidth(), lblhinhxe.getHeight(), Image.SCALE_SMOOTH));
                lblhinhxe.setIcon(imageIcon);
            }
        
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_lblxemanhMouseClicked

    private void lblnhaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnhaccMouseClicked
        new GUINhaCungCap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblnhaccMouseClicked

    private void lblthongtinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthongtinMouseClicked
        new GUIThongtin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblthongtinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIThongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIThongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIThongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIThongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIThongke().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbnam;
    private javax.swing.JComboBox<String> cmbthang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JLabel lbldangxuat;
    private javax.swing.JLabel lblhinhxe;
    private javax.swing.JLabel lblhoadon;
    private javax.swing.JLabel lblkhachhang;
    private javax.swing.JLabel lblnhacc;
    private javax.swing.JLabel lblnhanvien;
    private javax.swing.JLabel lblsl;
    private javax.swing.JLabel lblsoluong;
    private javax.swing.JLabel lbltenxe;
    private javax.swing.JLabel lblthoat;
    private javax.swing.JLabel lblthongke;
    private javax.swing.JLabel lblthongtin;
    private javax.swing.JLabel lbltongdoanhthu;
    private javax.swing.JLabel lbltongsl;
    private javax.swing.JLabel lblxe;
    private javax.swing.JLabel lblxemanh;
    private javax.swing.JLabel lblxemtk;
    private javax.swing.JTable tblNhaCungCap;
    private javax.swing.JLabel tieudetk;
    // End of variables declaration//GEN-END:variables
}
