/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doanxemay;

import Connectdatabase.Connect;
import Controll.DanhsachXe;
import Controll.Dulieubang;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.primefaces.component.autocomplete.AutoComplete;

/**
 * Chức năng: Tạo giao diện quản lí xe máy
 * 
 * @author: Phan Duy Tuấn
 * 
 * Ngày: 01/10/2019
 */
public class GUIXeMay extends javax.swing.JFrame {
    public static String sql = "SELECT * from dbo.[XeMay] x join dbo.[NhaCungCap] n on x.maNhaCungCap=n.maNhaCungCap join dbo.[LoaiXe] l on l.maLoaiXe=x.maLoaiXe";
    public static String maXe;
    public static int maLoaiXe;
    public static String maNhacc;
    String filename = null;
    byte[] xe_image= null;
    /**
     * Creates new form saudn
     */
    public GUIXeMay() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        showcombobox();
        showDuLieu();
        AutoCompleteDecorator.decorate(cmbloaixe);
        AutoCompleteDecorator.decorate(cmbnuocsx);
        AutoCompleteDecorator.decorate(cmbnhacc);
        AutoCompleteDecorator.decorate(cmbloaitk);
        DanhsachXe.loadDuLieuXe(sql, tblXeMay);
        Crt(false);
        chucnang(false);
        
    }
    /**
     *  Chức năng: Ẩn hiện các nút và các ô nhập
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày 01/10/2019
     * 
     * @param b : Giá trị true hoặc false
     */
    public void Crt(boolean b){
        txttenxe.setEnabled(b);
        txtmauxe.setEnabled(b);
        txtsoluong.setEnabled(b);
        txtdongia.setEnabled(b);
        cmbloaixe.setEnabled(b);
        cmbnuocsx.setEnabled(b);
        txtphankhoi.setEnabled(b);
        txtkhoiluong.setEnabled(b);
        txtphienban.setEnabled(b);
        cmbnhacc.setEnabled(b);
   
    }
    /**
     * Chức năng: Đẩy giá trị của tên nhà cung cấp và tên loại xe vào combobox
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày: 01/10/2019
     */
    public void showcombobox(){
        Connection connection = Connect.getConnect();
        try {
                    String sql1="Select * from dbo.[NhaCungCap]";
                    PreparedStatement ps = connection.prepareStatement(sql1);
                    ResultSet rs = ps.executeQuery();
                    
                    
                    while(rs.next()){                  
                        this.cmbnhacc.addItem(rs.getString("tenNhaCungCap"));
                        
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                try {
                    
                    String sql2="Select * from dbo.[LoaiXe]";
                    PreparedStatement ps = connection.prepareStatement(sql2);
                    ResultSet rs = ps.executeQuery();
                    while(rs.next()){                  
                        this.cmbloaixe.addItem(rs.getString("loaiXe"));
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
    }
    /**
     * Chức năng: Ẩn hiện các nút lưu, xóa, sửa, chọn ảnh
     * 
     * @param  a : Giá trị true hoặc false
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày : 1/10/2019
     */
    public void chucnang(boolean a){
        btnsua.setEnabled(a);
        btnxoa.setEnabled(a);
        btnluu.setEnabled(a);
        btnchonanh.setEnabled(a);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblxe = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblhoadon = new javax.swing.JLabel();
        lbldangxuat = new javax.swing.JLabel();
        lblkhachhang = new javax.swing.JLabel();
        lblnhanvien = new javax.swing.JLabel();
        lblnhacc = new javax.swing.JLabel();
        lblthongke = new javax.swing.JLabel();
        lblthongtin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblthoat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblXeMay = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txttenxe = new javax.swing.JTextField();
        txtmauxe = new javax.swing.JTextField();
        txtsoluong = new javax.swing.JTextField();
        txtdongia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtphankhoi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtkhoiluong = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtphienban = new javax.swing.JTextField();
        lblanh = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbnhacc = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnchonanh = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnluu = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        txttimkiem = new javax.swing.JTextField();
        cmbloaitk = new javax.swing.JComboBox<>();
        cmbloaixe = new javax.swing.JComboBox<>();
        cmbnuocsx = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblmaxe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(76, 95, 107));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 743));

        label1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Phan Duy Tuấn");

        class RoundedPanel extends JPanel
        {
            private Color backgroundColor;
            private int cornerRadius = 15;
            public RoundedPanel(LayoutManager layout, int radius) {
                super(layout);
                cornerRadius = radius;
            }
            public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
                super(layout);
                cornerRadius = radius;
                backgroundColor = bgColor;
            }
            public RoundedPanel(int radius) {
                super();
                cornerRadius = radius;

            }
            public RoundedPanel(int radius, Color bgColor) {
                super();
                cornerRadius = radius;
                backgroundColor = bgColor;
            }
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Dimension arcs = new Dimension(cornerRadius, cornerRadius);
                int width = getWidth();
                int height = getHeight();
                Graphics2D graphics = (Graphics2D) g;
                graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                //Draws the rounded panel with borders.
                if (backgroundColor != null) {
                    graphics.setColor(backgroundColor);
                } else {
                    graphics.setColor(getBackground());
                }
                graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
                graphics.setColor(getForeground());
                //            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
                //
            }
        }

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/Anhdaidien.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lblxe.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblxe.setForeground(new java.awt.Color(255, 255, 255));
        lblxe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblxe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/xemay_chon.png"))); // NOI18N
        lblxe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblxe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblxeMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("duytuan");

        lblhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/HoaDon_khongchon.png"))); // NOI18N
        lblhoadon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhoadonMouseClicked(evt);
            }
        });

        lbldangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dangxuat.png"))); // NOI18N
        lbldangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldangxuatMouseClicked(evt);
            }
        });

        lblkhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/khachhang_khongchon.png"))); // NOI18N
        lblkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblkhachhangMouseClicked(evt);
            }
        });

        lblnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/nhanvien_khongchon.png"))); // NOI18N
        lblnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnhanvienMouseClicked(evt);
            }
        });

        lblnhacc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/NhaCC_khongchon.png"))); // NOI18N
        lblnhacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnhaccMouseClicked(evt);
            }
        });

        lblthongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/Khongchon_Thongke.png"))); // NOI18N
        lblthongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblthongkeMouseClicked(evt);
            }
        });

        lblthongtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/Thongtin_khongchon.png"))); // NOI18N
        lblthongtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblthongtinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblnhacc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblkhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbldangxuat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblhoadon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblxe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblthongke))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblthongtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lbldangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(lblxe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnhacc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblthongke)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblthongtin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(567, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        lblthoat.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        lblthoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        lblthoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblthoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblthoatMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 95, 107));
        jLabel1.setText("Thông tin xe");

        tblXeMay.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        tblXeMay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblXeMay.setRowHeight(30);
        tblXeMay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblXeMayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblXeMay);

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(76, 95, 107));
        jLabel5.setText("Tên xe");

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(76, 95, 107));
        jLabel6.setText("Màu xe");

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(76, 95, 107));
        jLabel7.setText("Số lượng");

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(76, 95, 107));
        jLabel8.setText("Đơn giá");

        txttenxe.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txttenxe.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));

        txtmauxe.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtmauxe.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));
        txtmauxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmauxeActionPerformed(evt);
            }
        });

        txtsoluong.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtsoluong.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));
        txtsoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsoluongActionPerformed(evt);
            }
        });

        txtdongia.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtdongia.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(76, 95, 107));
        jLabel9.setText("Loại xe");

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(76, 95, 107));
        jLabel10.setText("Nước SX");

        jLabel11.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(76, 95, 107));
        jLabel11.setText("Phân khối");

        txtphankhoi.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtphankhoi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));
        txtphankhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphankhoiActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(76, 95, 107));
        jLabel12.setText("Khối lượng");

        txtkhoiluong.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtkhoiluong.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));

        jLabel13.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(76, 95, 107));
        jLabel13.setText("Phiên bản");

        txtphienban.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtphienban.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));
        txtphienban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphienbanActionPerformed(evt);
            }
        });

        lblanh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblanh.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(76, 95, 107));
        jLabel15.setText("Ảnh xe");

        cmbnhacc.setEditable(true);
        cmbnhacc.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        cmbnhacc.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbnhaccPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbnhacc.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cmbnhaccComponentShown(evt);
            }
        });
        cmbnhacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbnhaccActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(76, 95, 107));
        jLabel16.setText("CC");

        jLabel23.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(76, 95, 107));
        jLabel23.setText("Kg");

        jLabel24.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(76, 95, 107));
        jLabel24.setText("VNĐ");

        btnchonanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/Chon_anh.png"))); // NOI18N
        btnchonanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonanhActionPerformed(evt);
            }
        });

        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/b_themxe.png"))); // NOI18N
        btnthem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));
        btnthem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/chinhsua.png"))); // NOI18N
        btnsua.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));
        btnsua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnluu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/luu.png"))); // NOI18N
        btnluu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));
        btnluu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/css/xoa.png"))); // NOI18N
        btnxoa.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 95, 107)));
        btnxoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        txttimkiem.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txttimkiem.setText("Tìm kiếm");
        txttimkiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttimkiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttimkiemFocusLost(evt);
            }
        });
        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimkiemKeyReleased(evt);
            }
        });

        cmbloaitk.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        cmbloaitk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên xe", "Loại xe", "Phân khối" }));

        cmbloaixe.setEditable(true);
        cmbloaixe.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        cmbloaixe.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbloaixePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        cmbnuocsx.setEditable(true);
        cmbnuocsx.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        cmbnuocsx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhật", "Đức", "Pháp", "Canada", "Hàn Quốc", "Việt Nam" }));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(76, 95, 107));
        jLabel2.setText("Tên NCC");

        jLabel3.setBackground(new java.awt.Color(76, 95, 107));
        jLabel3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel3.setText("Mã xe");

        lblmaxe.setBackground(new java.awt.Color(76, 95, 107));
        lblmaxe.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblmaxe.setText("jLabel4");
        lblmaxe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 95, 107)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnthem)
                                        .addGap(58, 58, 58)
                                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(91, 91, 91)
                                        .addComponent(btnluu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(94, 94, 94)
                                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 264, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtmauxe, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                                    .addComponent(cmbnhacc, 0, 323, Short.MAX_VALUE)
                                                    .addComponent(txttenxe, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                                    .addComponent(lblmaxe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtphienban, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnchonanh, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(txtphankhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(txtkhoiluong, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(cmbnuocsx, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmbloaixe, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblanh, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(508, 508, 508)
                                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(cmbloaitk, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbloaitk)
                            .addComponent(txttimkiem)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbloaixe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblmaxe, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cmbnuocsx, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txttenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtphankhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmbnhacc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtkhoiluong, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtmauxe, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtphienban, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24))
                                    .addComponent(btnchonanh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblanh, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnthem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnluu, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnxoa, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsua)))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1568, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblthoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthoatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblthoatMouseClicked

    private void lblxeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblxeMouseClicked
        
    }//GEN-LAST:event_lblxeMouseClicked

    private void cmbnhaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbnhaccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbnhaccActionPerformed

    private void txtmauxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmauxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmauxeActionPerformed

    private void txtsoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsoluongActionPerformed
    /**
     * chức năng: Đẩy 1 giá trị xe lên giao diện
     * 
     * @author: Phan Duy Tuấn
     * 
     * @Ngày : 2/10/2019
     */
    private void showDuLieu(){
        Connection connection= Connect.getConnect();
            String query="SELECT * from dbo.[XeMay] x join dbo.[NhaCungCap] n on x.maNhaCungCap=n.maNhaCungCap join dbo.[LoaiXe] l on l.maLoaiXe=x.maLoaiXe order by maXe asc";
        try {           
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()) {        
                this.lblmaxe.setText(rs.getString("maXe"));                   
                    this.txttenxe.setText(rs.getString("tenXe"));
                    this.txtmauxe.setText(rs.getString("mauXe"));
                    this.txtsoluong.setText(rs.getString("soLuong"));
                    DecimalFormat df = new DecimalFormat("###,000");
                    this.txtdongia.setText(df.format(rs.getDouble("donGiaNhap")));
                    maNhacc=rs.getString("maNhaCungCap");
                    maLoaiXe=rs.getInt("maLoaiXe");
                    this.cmbloaixe.setSelectedItem(rs.getString("loaiXe"));
                    this.cmbnuocsx.setSelectedItem(rs.getString("nuocSX"));
                    this.txtphankhoi.setText(rs.getString("phanKhoi"));
                    this.txtkhoiluong.setText(rs.getString("khoiLuong"));
                    this.txtphienban.setText(rs.getString("phienBan"));               
                    this.cmbnhacc.setSelectedItem(rs.getString("tenNhaCungCap"));
                    
                    byte[] img = rs.getBytes("imageXM");
                    ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblanh.getWidth(), lblanh.getHeight(), Image.SCALE_SMOOTH));
                    this.lblanh.setIcon(imageIcon);
                    
            }
            
        } catch (Exception e) {
             
        }
    }

    private void cmbnhaccComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cmbnhaccComponentShown
        
    }//GEN-LAST:event_cmbnhaccComponentShown
    /**
     * Chức năng: Nhấp một chiếc xe bất kì thông tin của xe hiển thị lên giao diện
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày: 5/10/2019
     */
    byte[] xemay_image=null;
    private void tblXeMayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblXeMayMouseClicked
        try {
                int row= this.tblXeMay.getSelectedRow();
                Crt(false);
                
                chucnang(true);
                btnluu.setEnabled(false);
                btnchonanh.setEnabled(false);
                String IDrow = (this.tblXeMay.getModel().getValueAt(row, 1)).toString();
                String sql1="SELECT * from dbo.[XeMay] x join dbo.[NhaCungCap] n on x.maNhaCungCap=n.maNhaCungCap join dbo.[LoaiXe] l on l.maLoaiXe=x.maLoaiXe where maXe='"+IDrow+"'";
                ResultSet rs = Dulieubang.ShowTextField(sql1);
                if(rs.next()){
                    maXe= rs.getString("maXe");
                    maLoaiXe= rs.getInt("maLoaiXe");
                    maNhacc= rs.getString("maNhaCungCap");
                    this.lblmaxe.setText(rs.getString("maXe"));
                    this.cmbnhacc.setSelectedItem(rs.getString("tenNhaCungCap"));
                    this.txttenxe.setText(rs.getString("tenXe"));
                    this.txtmauxe.setText(rs.getString("mauXe"));
                    this.txtsoluong.setText(rs.getString("soLuong"));
                    DecimalFormat df = new DecimalFormat("###,000");
                    this.txtdongia.setText(df.format(rs.getDouble("donGiaNhap")));
                    this.cmbloaixe.setSelectedItem(rs.getString("loaiXe"));
                    this.cmbnuocsx.setSelectedItem(rs.getString("nuocSX"));
                    this.txtphankhoi.setText(rs.getString("phanKhoi"));
                    this.txtkhoiluong.setText(rs.getString("khoiLuong"));
                    this.txtphienban.setText(rs.getString("phienBan"));
                    byte[] img = rs.getBytes("imageXM");
                    ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblanh.getWidth(), lblanh.getHeight(), Image.SCALE_SMOOTH));
                    lblanh.setIcon(imageIcon);
                    
                }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_tblXeMayMouseClicked
    /**
     * Chức năng: Chuyển sang giao diện hóa đơn
     * 
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày 2/10/2019
     */
    private void lblhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhoadonMouseClicked
        new GUIHoaDon().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblhoadonMouseClicked
    /**
     * Chức năng: Chọn ảnh
     * 
     * @author : Phan Duy Tuấn
     * 
     * Ngày: 2/11/2019
     */
    private void btnchonanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonanhActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon= new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lblanh.getWidth(), lblanh.getHeight(), Image.SCALE_SMOOTH));
        lblanh.setIcon(imageIcon);
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum; (readNum=fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
            }
            xe_image= bos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnchonanhActionPerformed
    /**
     * Chức năng: Làm rỗng các ô trên gao diện để nhập
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày 2/10/2019
     */
    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        Crt(true);
        btnluu.setEnabled(true);
        btnchonanh.setEnabled(true);
        btnsua.setEnabled(false);
        this.lblmaxe.setText("Tự động phát sinh");
        this.txttenxe.setText("");
        this.txtmauxe.setText("");
        this.txtsoluong.setText("");
        this.txtdongia.setText("");
        
        this.txtphankhoi.setText("");
        this.txtkhoiluong.setText("");
        this.txtphienban.setText("");
        this.txttenxe.requestFocus();
    }//GEN-LAST:event_btnthemActionPerformed
    /**
     * Chức năng: Cho phép chỉnh sửa xe
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày: 2/10/2019
     */
    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        Connection connection = Connect.getConnect();
        btnluu.setEnabled(true);
        btnchonanh.setEnabled(true);
        if(lblmaxe.getText().length()==0 || lblmaxe.getText()=="Tự động phát sinh"){
            JOptionPane.showMessageDialog(null, "Bạn phải chọn xe cần sửa","Thông báo",1);
        }
        else{
                Crt(true);
                
        }
    }//GEN-LAST:event_btnsuaActionPerformed
    /**
     * Chức năng: Thực hiện chức năng sửa và thêm xe, kiểm tra ràng buộc 
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày : 22/10/2019
     */
    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed

            int error=0;
            if (this.txttenxe.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Tên xe không được để trống");
                error=1;
            }
            else{
                error=0;
            }
            int error2=0;
            if(this.txtmauxe.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Màu xe không được để trống");
                error2=1;
            }
            else{
                error2=0;
            }
            int error3=0;
            if(this.txtsoluong.getText().equals("")){
                
                JOptionPane.showMessageDialog(this, "Số lượng không được để trống");
                error3=1;
            }
            else{
                error3=0;
            }
            int error4=0;
            if(this.txtdongia.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Đơn giá không được để trống");
                error4=1;
            }
            else{
                error4=0;
            }
            int error5=0;
            if(this.txtphankhoi.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Phân khối không được để trống");
                error5=1;
            }
            else{
                error5=0;
            }
            int error6=0;
            if(this.txtkhoiluong.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Khối lượng không được để trống");
                error6=1;
            }     
            else{
                error6=0;
            }
            int error7=0;
            if(this.txtphienban.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Phiên bản không được để trống");   
                error7=1;
            }
            else{
                error7=0;
            }
            if(error==1 || error2==1 || error3==1 || error4==1 || error5==1 || error6==1 || error7==1){
                if(this.lblmaxe.getText()=="Tự động phát sinh"){
                    JOptionPane.showMessageDialog(this, "Thêm thông tin xe thất bại");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Sửa thông tin xe thất bại");
                }
            }
            else{
                if(this.lblmaxe.getText()=="Tự động phát sinh"){
                DanhsachXe.ThemXe("100", this.txttenxe.getText(), this.txtmauxe.getText(),Integer.parseInt(this.txtsoluong.getText()), Double.parseDouble(this.txtdongia.getText()),maLoaiXe ,
                    this.cmbnuocsx.getSelectedItem().toString(),Integer.parseInt(this.txtphankhoi.getText()) , Float.parseFloat(this.txtkhoiluong.getText()), this.txtphienban.getText()
                    , maNhacc,xe_image);
                DanhsachXe.loadDuLieuXe(sql, tblXeMay);
                }
                else{
                    if(this.lblmaxe.getText().length()==0){
                        JOptionPane.showMessageDialog(null, "Bạn phải chọn xe cần sửa","Thông báo",1);
                    }
                    else{
                        if(JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn sửa xe có mã là "+maXe+" hay không ?","Thông báo",2)==0){
                            DanhsachXe.SuaXe(maXe, this.txttenxe.getText(), this.txtmauxe.getText(),Integer.parseInt(this.txtsoluong.getText()), Double.parseDouble(this.txtdongia.getText()), maLoaiXe,
                                this.cmbnuocsx.getSelectedItem().toString(),Integer.parseInt(this.txtphankhoi.getText()) , Float.parseFloat(this.txtkhoiluong.getText()), this.txtphienban.getText()
                                , maNhacc, xe_image);
                            DanhsachXe.loadDuLieuXe(sql, tblXeMay);
                        }

                    }

                    }
            }
        
    }//GEN-LAST:event_btnluuActionPerformed
    /**
     * Chức năng: Thực hiện chức năng xóa xe
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày: 2/10/2019
     */
    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa xe có mã là "+maXe+" hay không ?","Thông báo",2)==0){
                DanhsachXe.XoaXe(maXe);
            DanhsachXe.loadDuLieuXe(sql, tblXeMay);   
            }
    }//GEN-LAST:event_btnxoaActionPerformed
    /**
     * Chức năng: Chuyển qua giao diện khách hàng
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày 1/10/2019
     */
    private void lblkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblkhachhangMouseClicked
        new GUIKhachHang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblkhachhangMouseClicked
    /**
     * Chức năng: Chuyển qua giao diện nhân viên
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày 1/10/2019
     */
    private void lblnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnhanvienMouseClicked
        new GUINhanVien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblnhanvienMouseClicked
    /**
     * Chức năng: Chuyển qua giao diện nhà cung cấp
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày 1/10/2019
     */
    private void lblnhaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnhaccMouseClicked
        new GUINhaCungCap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblnhaccMouseClicked
    
    private void txttimkiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttimkiemFocusGained
        if(txttimkiem.getText().equals("Tìm kiếm")){
            this.txttimkiem.setText("");
        }
    }//GEN-LAST:event_txttimkiemFocusGained

    private void txttimkiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttimkiemFocusLost
        if(txttimkiem.getText().equals("")){
            this.txttimkiem.setText("Tìm kiếm");
        }
    }//GEN-LAST:event_txttimkiemFocusLost
    /**
     * Chức năng: Tìm kiếm thông tin xe trong bảng
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày 3/10/2019
     */
    private void txttimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyReleased
        if(txttimkiem.getText().length()==0){
            DanhsachXe.loadDuLieuXe(sql, tblXeMay);
        }
        else{
            
            if(cmbloaitk.getSelectedItem()=="Tên xe"){
                String sqltenxe = "Select * from dbo.[XeMay] where tenXe like '%"+this.txttimkiem.getText()+"%'";
                DanhsachXe.TimtenXe(sqltenxe, tblXeMay, this.txttimkiem.getText());
            }
            if(cmbloaitk.getSelectedItem()=="Loại xe"){
                String sqlloaixe = "Select * from dbo.[XeMay] where loaiXe like '%"+this.txttimkiem.getText()+"%'";
                DanhsachXe.timloaixe(sqlloaixe, tblXeMay, this.txttimkiem.getText());
            }
            if(cmbloaitk.getSelectedItem()=="Phân khối"){
                String sqlphankhoi = "Select * from dbo.[XeMay] where phanKhoi="+Float.parseFloat(this.txttimkiem.getText())+"";
                DanhsachXe.Timpkxe(sqlphankhoi, tblXeMay, Float.parseFloat(this.txttimkiem.getText()));
            }
        }
        
    }//GEN-LAST:event_txttimkiemKeyReleased

    private void txtphienbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphienbanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphienbanActionPerformed
    /**
     * Chức năng: Đăng xuất khỏi chương trình
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày 1/10/2019
     */
    private void lbldangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangxuatMouseClicked
        new JFrameGiaodien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbldangxuatMouseClicked

    private void txtphankhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphankhoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphankhoiActionPerformed
    /**
     * Chức năng: Tìm kiếm tên nhà cung cấp trong combobox
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày 30/10/2019
     */
    private void cmbnhaccPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbnhaccPopupMenuWillBecomeInvisible
        Connection connection = Connect.getConnect();
        String sqlma = "select * from NhaCungCap where tenNhaCungCap=?";
        try {
            DecimalFormat df= new DecimalFormat("###,000 VNĐ");
            PreparedStatement ps = connection.prepareStatement(sqlma);
            ps.setString(1, this.cmbnhacc.getSelectedItem().toString());
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {      
                maNhacc= rs.getString("maNhaCungCap");
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_cmbnhaccPopupMenuWillBecomeInvisible
    /**
     * Chức năng: Tìm kiếm tên loại xe trong combobox 
     * 
     * @author: Phan Duy Tuấn
     * 
     * Ngày 30/10/2019
     */
    private void cmbloaixePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbloaixePopupMenuWillBecomeInvisible
        Connection connection = Connect.getConnect();
        String sqlma = "select * from LoaiXe where loaiXe=?";
        try {
            DecimalFormat df= new DecimalFormat("###,000 VNĐ");
            PreparedStatement ps = connection.prepareStatement(sqlma);
            ps.setString(1, this.cmbloaixe.getSelectedItem().toString());
            ResultSet rs = ps.executeQuery();
            if(rs.next()) {     
                maLoaiXe= rs.getInt("maLoaiXe");
                
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_cmbloaixePopupMenuWillBecomeInvisible

    private void lblthongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthongkeMouseClicked
        new GUIThongke().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblthongkeMouseClicked

    private void lblthongtinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthongtinMouseClicked
        new GUIThongtin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblthongtinMouseClicked
    
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIXeMay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIXeMay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIXeMay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIXeMay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIXeMay().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchonanh;
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cmbloaitk;
    private javax.swing.JComboBox<String> cmbloaixe;
    private javax.swing.JComboBox<String> cmbnhacc;
    private javax.swing.JComboBox<String> cmbnuocsx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JLabel lblanh;
    private javax.swing.JLabel lbldangxuat;
    private javax.swing.JLabel lblhoadon;
    private javax.swing.JLabel lblkhachhang;
    private javax.swing.JLabel lblmaxe;
    private javax.swing.JLabel lblnhacc;
    private javax.swing.JLabel lblnhanvien;
    private javax.swing.JLabel lblthoat;
    private javax.swing.JLabel lblthongke;
    private javax.swing.JLabel lblthongtin;
    private javax.swing.JLabel lblxe;
    private javax.swing.JTable tblXeMay;
    private javax.swing.JTextField txtdongia;
    private javax.swing.JTextField txtkhoiluong;
    private javax.swing.JTextField txtmauxe;
    private javax.swing.JTextField txtphankhoi;
    private javax.swing.JTextField txtphienban;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttenxe;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
